name: CI

on:
  push:
    branches: [ main]
  pull_request:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    environment: Production
    strategy:
      matrix:
        node: [20, 22]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run Jest (coverage + junit)
        env:
          CI: "true"
          NODE_ENV: test
          NODE_OPTIONS: --experimental-vm-modules
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: npm run test:ci

      # Export swagger.json (butuh script export:swagger)
      - name: Export Swagger spec
        run: npm run export:swagger

      # Upload artefak
      - name: Upload coverage
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-node${{ matrix.node }}
          path: coverage

      - name: Upload JUnit report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-node${{ matrix.node }}
          path: reports/junit.xml

      - name: Upload Swagger spec
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: swagger-spec
          path: artifacts/swagger.json
